diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=schannel
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
user.name=Boda5211
user.email=bodab5211@gmail.com
safe.directory=D:/Project/nodejs-ecommerce-api-v2
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/AbdullahMostafak/nodejs-ecommerce.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
user.name=AbdullahMostafak
